name: Deploy Front
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'front/**'
    tags:
      - 'v*'

jobs:
  Build:
    uses: ap1402/CID-CD-POC/.github/workflows/frontend-build.yml@dev

  DeployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download Artifac
        uses: actions/download-artifact@v2
        with:
          name: front
          path: dist
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region us-east-2 \
            dist/front-poc s3://angular-bucket-poc
